version: "3.7"

services:
  app:
    image: node:14
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USER: root
      MONGODB_PASSWORD: secret
      MONGODB_DB: bank

  mongodb:
    image: mongo
    volumes:
      - bank-mongodb-data:/var/lib/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME: badbank
      - MONGO_INITDB_ROOT_PASSWORD: database

volumes:
  bank-mongodb-data:
